name: NSLS-II-MIDAS
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.7

  - pip:
    - h5py
    - numpy
    - pandas
    - pyqt5
    - pyqtgraph==0.12.2
    - pystackreg
    - scikit-image
    - scikit-learn
    - scipy>=1.7
    - tifffile
    - xraylarch==0.9.51
    - pyshortcuts
    - opencv-python


